# Generated by Django 5.2.7 on 2025-10-21 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Turismo Hospitality', max_length=200)),
                ('institution_slogan', models.CharField(default='Excelencia en Educación Turística', max_length=300)),
                ('contact_email', models.EmailField(default='contacto@turismohospitality.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+58 123-456-7890', max_length=20)),
                ('simulation_duration', models.IntegerField(default=30, help_text='Duración en minutos')),
                ('max_attempts', models.IntegerField(default=3, help_text='Intentos máximos por simulación')),
                ('passing_score', models.IntegerField(default=70, help_text='Puntuación mínima para aprobar')),
                ('max_students', models.IntegerField(default=500, help_text='Límite de estudiantes activos')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=2)),
                ('timezone', models.CharField(choices=[('America/Caracas', 'Caracas (UTC-4)'), ('America/Mexico_City', 'Ciudad de México (UTC-6)'), ('America/Bogota', 'Bogotá (UTC-5)')], default='America/Caracas', max_length=50)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', 'DD/MM/AAAA'), ('mm/dd/yyyy', 'MM/DD/AAAA'), ('yyyy-mm-dd', 'AAAA-MM-DD')], default='dd/mm/yyyy', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('VES', 'VES (Bs.)')], default='VES', max_length=3)),
                ('theme', models.CharField(choices=[('default', 'Tema Predeterminado'), ('dark', 'Tema Oscuro'), ('ocean', 'Tema Océano'), ('nature', 'Tema Naturaleza')], default='default', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_backup', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Backup',
                'verbose_name_plural': 'Historial de Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='UTD Francisco Tamayo', max_length=200)),
                ('semester', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre')], default=1)),
                ('career', models.CharField(default='Turismo', max_length=100)),
                ('specialization', models.CharField(choices=[('recepcion', 'Recepción Hotelera'), ('reservas', 'Gestión de Reservas'), ('eventos', 'Organización de Eventos'), ('alimentos', 'Alimentos y Bebidas')], default='recepcion', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('practice_reminders', models.BooleanField(default=True)),
                ('progress_updates', models.BooleanField(default=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('total_simulations', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('achievements_unlocked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
