# Generated by Django 5.2.3 on 2025-11-01 22:49

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_systemsettings_backuphistory_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='codigo_reserva',
            field=models.CharField(default=myapp.models.generar_codigo_reserva, editable=False, max_length=9, unique=True),
        ),
    ]
